version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: finai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /mnt/dados/finai/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d finai"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./apps/api
    env_file: ./apps/api/.env
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

  web:
    build: ./apps/web
    env_file: ./apps/web/.env
    ports:
      - "3000:3000"
    depends_on:
      - api
