version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: finai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d finai"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: ramonmirandaa-crypto/finai-api:latest
    environment:
      PORT: 4000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: finai
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: devsecret
      FRONTEND_ORIGIN: http://localhost:3000
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy

  web:
    image: ramonmirandaa-crypto/finai-web:latest
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  pgdata:
